### ISSUE TITLE
READMEにプロジェクト環境構築やインストール方法を記載する

### ISSUE THREAD

**Issue by ptrkdan** [nokia0315/Python-practice#5]
ローカルでどのようにソースをインストールしたり環境構築したりするという手順を書いた方が良いと思います。
[こちら](https://github.com/pallets/flask#installing)のようにレポジトリのルートフォルダーに`README.md`を追加してお願いできますか。

**Comment by nokia0315** [comment]
I made Readme.md.
Could you please confirm this?

**Comment by nokia0315** [comment]
Thank you very much for correcting my English！

I will fix that tomorrow 🙋‍♂️
